import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css"
import Header from "@/app/components/header/Header";
import Footer from "@/app/components/footer/Footer";
import BackToTopButton from "@/app/components/backToTopButton/BackToTopButton";
import MouseFollowerCircle from "@/app/components/mouseFollowerCircle/MouseFollowerCircle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-[#1a0d21]  bg-repeat text-[#DEDEDE] overflow-hidden`}
        style={{ backgroundImage: "url('/img/body-bg.jpg')" }} >

        <Header />

        {children}

        <MouseFollowerCircle />
        <Footer />
        <BackToTopButton />
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}
